# Generated by Django 4.0.4 on 2022-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbdis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droughtindex',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
